<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $categoryId = fn (string $name) => Category::where('name', $name)->firstOrFail()->id;

        $products = [
            [
                'category_id' => $categoryId('AI Chat'),
                'name' => 'Gemini Pro',
                'description' => 'Akses penuh Gemini Pro untuk percakapan AI yang lebih cerdas, cepat, dan akurat. Cocok untuk menulis, coding, riset, dan pekerjaan kreatif setiap hari. Pakai langsung di akun pribadimu dengan garansi aman.',
                'price' => 30000,
                'original_price' => 45000,
                'duration' => '3 bulan',
                'warranty' => '1 bulan',
                'icon' => 'auto_awesome',
                'rating' => 5,
                'badge' => 'Terlaris',
                'available' => true,
                'sort' => 1,
            ],
            [
                'category_id' => $categoryId('AI Chat'),
                'name' => 'ChatGPT Plus',
                'description' => 'ChatGPT Plus membuka akses ke model GPT terbaru, respon lebih cepat, dan fitur unggulan saat jam sibuk. Ideal untuk pekerja, pelajar, dan kreator konten yang butuh AI andal.',
                'price' => 250000,
                'original_price' => 300000,
                'duration' => '1 bulan',
                'warranty' => '1 bulan',
                'icon' => 'smart_toy',
                'rating' => 5,
                'badge' => null,
                'available' => true,
                'sort' => 2,
            ],
            [
                'category_id' => $categoryId('Video Editor'),
                'name' => 'CapCut Pro',
                'description' => 'Semua fitur premium CapCut terbuka: hapus background, transisi eksklusif, efek sinematik, dan tanpa watermark. Wajib bagi editor video dan kreator TikTok.',
                'price' => 25000,
                'original_price' => 45000,
                'duration' => '1 bulan',
                'warranty' => '1 bulan',
                'icon' => 'video_settings',
                'rating' => 4,
                'badge' => 'Populer',
                'available' => true,
                'sort' => 3,
            ],
            [
                'category_id' => $categoryId('Desain'),
                'name' => 'Canva Pro',
                'description' => 'Bebas pakai jutaan template premium, background transparan, magic resize, dan font eksklusif. Desain jadi lebih cepat dan profesional untuk kebutuhan apa pun.',
                'price' => 35000,
                'original_price' => 50000,
                'duration' => '1 bulan',
                'warranty' => '1 bulan',
                'icon' => 'palette',
                'rating' => 5,
                'badge' => null,
                'available' => true,
                'sort' => 4,
            ],
            [
                'category_id' => $categoryId('Musik'),
                'name' => 'Spotify Premium',
                'description' => 'Nikmati musik tanpa iklan, bisa download lagu untuk offline, dan kualitas suara terbaik. Akun premium dipasang langsung untukmu.',
                'price' => 15000,
                'original_price' => 25000,
                'duration' => '1 bulan',
                'warranty' => '1 minggu',
                'icon' => 'music_note',
                'rating' => 4,
                'badge' => null,
                'available' => true,
                'sort' => 5,
            ],
            [
                'category_id' => $categoryId('Streaming'),
                'name' => 'Netflix Premium',
                'description' => 'Tonton semua film dan serial di kualitas 4K dengan layar hingga 4 perangkat. Akun dibagikan ke kamu dengan garansi dan dukungan penuh.',
                'price' => 35000,
                'original_price' => 55000,
                'duration' => '1 bulan',
                'warranty' => '1 bulan',
                'icon' => 'subscriptions',
                'rating' => 5,
                'badge' => null,
                'available' => true,
                'sort' => 6,
            ],
            [
                'category_id' => $categoryId('Streaming'),
                'name' => 'YouTube Premium',
                'description' => 'Tonton video tanpa iklan, putar di background, dan akses YouTube Music Premium. Langganan langsung aktif.',
                'price' => 22000,
                'original_price' => 38000,
                'duration' => '1 bulan',
                'warranty' => '1 bulan',
                'icon' => 'play_circle',
                'rating' => 5,
                'badge' => 'Terlaris',
                'available' => true,
                'sort' => 7,
            ],
            [
                'category_id' => $categoryId('Video Editor'),
                'name' => 'Adobe Premiere Pro',
                'description' => 'Software editing video standar industri. Semua fitur tersedia untuk hasil profesional.',
                'price' => 45000,
                'original_price' => 80000,
                'duration' => '1 bulan',
                'warranty' => '1 minggu',
                'icon' => 'movie',
                'rating' => 4,
                'badge' => null,
                'available' => true,
                'sort' => 8,
            ],
            [
                'category_id' => $categoryId('Desain'),
                'name' => 'Figma Professional',
                'description' => 'Desain UI/UX kolaboratif dengan semua fitur professional. Cocok untuk tim desain dan developer.',
                'price' => 40000,
                'original_price' => 65000,
                'duration' => '1 bulan',
                'warranty' => '1 bulan',
                'icon' => 'design_services',
                'rating' => 5,
                'badge' => null,
                'available' => true,
                'sort' => 9,
            ],
            [
                'category_id' => $categoryId('Desain'),
                'name' => 'Lightroom CC',
                'description' => 'Edit foto dengan presisi penuh, preset eksklusif, dan cloud storage. Wajib untuk fotografer.',
                'price' => 28000,
                'original_price' => 42000,
                'duration' => '1 bulan',
                'warranty' => '1 bulan',
                'icon' => 'photo_camera',
                'rating' => 4,
                'badge' => null,
                'available' => true,
                'sort' => 10,
            ],
            [
                'category_id' => $categoryId('Musik'),
                'name' => 'YouTube Music',
                'description' => 'Streaming musik tanpa iklan dengan kualitas terbaik dan download offline.',
                'price' => 15000,
                'original_price' => 25000,
                'duration' => '1 bulan',
                'warranty' => '1 minggu',
                'icon' => 'library_music',
                'rating' => 4,
                'badge' => null,
                'available' => true,
                'sort' => 11,
            ],
            [
                'category_id' => $categoryId('AI Chat'),
                'name' => 'Claude Pro',
                'description' => 'Asisten AI dari Anthropic dengan konteks besar dan analisis dokumen canggih.',
                'price' => 300000,
                'original_price' => 400000,
                'duration' => '1 bulan',
                'warranty' => '1 bulan',
                'icon' => 'science',
                'rating' => 5,
                'badge' => null,
                'available' => true,
                'sort' => 12,
            ],
            [
                'category_id' => $categoryId('Video Editor'),
                'name' => 'VN Editor',
                'description' => 'Editor video tanpa watermark, transisi lengkap, dan efek eksklusif untuk konten pendek.',
                'price' => 12000,
                'original_price' => 20000,
                'duration' => '1 bulan',
                'warranty' => '1 minggu',
                'icon' => 'movie_edit',
                'rating' => 4,
                'badge' => null,
                'available' => true,
                'sort' => 13,
            ],
            [
                'category_id' => $categoryId('Desain'),
                'name' => 'Picsart Gold',
                'description' => 'Desain, edit foto, dan kolase dengan jutaan stiker serta aset premium.',
                'price' => 18000,
                'original_price' => 30000,
                'duration' => '1 bulan',
                'warranty' => '1 minggu',
                'icon' => 'image',
                'rating' => 4,
                'badge' => null,
                'available' => true,
                'sort' => 14,
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(['name' => $product['name']], $product);
        }
    }
}
