<?php

namespace App\Filament\Resources\Products\Pages\Concerns;

use Illuminate\Support\Facades\Storage;

trait HandlesProductImageUpload
{
    protected string|array|null $productImageUpload = null;

    /**
     * Put the existing media path into the FileUpload preview when editing.
     *
     * @param  array<string, mixed>  $data
     * @return array<string, mixed>
     */
    protected function mutateFormDataBeforeFill(array $data): array
    {
        $data['images'] = $this->getRecord()->getFirstMedia('images')?->getPathRelativeToRoot();

        return $data;
    }

    /**
     * Keep the upload path out of the products table data.
     *
     * @param  array<string, mixed>  $data
     * @return array<string, mixed>
     */
    protected function captureProductImage(array $data): array
    {
        $this->productImageUpload = $data['images'] ?? null;
        unset($data['images']);

        return $data;
    }

    protected function syncProductImage(): void
    {
        $path = is_array($this->productImageUpload)
            ? ($this->productImageUpload[0] ?? null)
            : $this->productImageUpload;
        $product = $this->getRecord();
        $currentMedia = $product->getFirstMedia('images');
        $currentPath = $currentMedia?->getPathRelativeToRoot();

        if ($path === $currentPath) {
            return;
        }

        if (blank($path)) {
            $product->clearMediaCollection('images');

            return;
        }

        $disk = Storage::disk('public');

        // The path is generated by FileUpload on the public disk.
        if (! $disk->exists($path)) {
            return;
        }

        $product->clearMediaCollection('images');
        $product
            ->addMediaFromDisk($path, 'public')
            ->toMediaCollection('images', 'public');

        // FileUpload is only used as a staging location; the media library owns
        // the final copy and its conversions.
        $disk->delete($path);
    }
}
