window.PRODUCTS = [
  {
    id: "gemini-pro",
    nama: "Gemini Pro",
    kategori: "AI Chat",
    harga: 30000,
    hargaCoret: 45000,
    masaAktif: "3 bulan",
    garansi: "1 bulan",
    ikon: "auto_awesome",
    rating: 5,
    deskripsi: "Akses penuh Gemini Pro untuk percakapan AI yang lebih cerdas, cepat, dan akurat. Cocok untuk menulis, coding, riset, dan pekerjaan kreatif setiap hari. Pakai langsung di akun pribadimu dengan garansi aman.",
  },
  {
    id: "chatgpt-plus",
    nama: "ChatGPT Plus",
    kategori: "AI Chat",
    harga: 250000,
    hargaCoret: 300000,
    masaAktif: "1 bulan",
    garansi: "1 bulan",
    ikon: "smart_toy",
    rating: 5,
    deskripsi: "ChatGPT Plus membuka akses ke model GPT terbaru, respon lebih cepat, dan fitur unggulan saat jam sibuk. Ideal untuk pekerja, pelajar, dan kreator konten yang butuh AI andal.",
  },
  {
    id: "capcut-pro",
    nama: "CapCut Pro",
    kategori: "Video Editor",
    harga: 25000,
    hargaCoret: 45000,
    masaAktif: "1 bulan",
    garansi: "1 bulan",
    ikon: "video_settings",
    rating: 4,
    deskripsi: "Semua fitur premium CapCut terbuka: hapus background, transisi eksklusif, efek sinematik, dan tanpa watermark. Wajib bagi editor video dan kreator TikTok.",
  },
  {
    id: "canva-pro",
    nama: "Canva Pro",
    kategori: "Desain",
    harga: 35000,
    hargaCoret: 50000,
    masaAktif: "1 bulan",
    garansi: "1 bulan",
    ikon: "palette",
    rating: 5,
    deskripsi: "Bebas pakai jutaan template premium, background transparan, magic resize, dan font eksklusif. Desain jadi lebih cepat dan profesional untuk kebutuhan apa pun.",
  },
  {
    id: "spotify-premium",
    nama: "Spotify Premium",
    kategori: "Musik",
    harga: 15000,
    hargaCoret: 25000,
    masaAktif: "1 bulan",
    garansi: "1 minggu",
    ikon: "music_note",
    rating: 4,
    deskripsi: "Nikmati musik tanpa iklan, bisa download lagu untuk offline, dan kualitas suara terbaik. Akun premium dipasang langsung untukmu.",
  },
  {
    id: "netflix-premium",
    nama: "Netflix Premium",
    kategori: "Streaming",
    harga: 35000,
    hargaCoret: 55000,
    masaAktif: "1 bulan",
    garansi: "1 bulan",
    ikon: "subscriptions",
    rating: 5,
    deskripsi: "Tonton semua film dan serial di kualitas 4K dengan layar hingga 4 perangkat. Akun dibagikan ke kamu dengan garansi dan dukungan penuh.",
  },
];

window.TESTIMONIALS = [
  { nama: "Rizky", role: "Mahasiswa", rating: 5, text: "Proses cepat banget, chat WhatsApp langsung dibalas. Gemini Pro-nya aman sampai sekarang, recommended!" },
  { nama: "Sinta", role: "Kreator Konten", rating: 5, text: "CapCut Pro tanpa watermark. Ini langganan bulanan saya, gak pernah kapok." },
  { nama: "Andi", role: "Freelance Desainer", rating: 4, text: "Canva Pro-nya murah dan masa aktif sesuai janji. Semoga makin banyak promo." },
];
